version: '2'
services:
  web:
    container_name: "servidor"
    image: "jorgelfant/kuberneteswildfly:develop"
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - base:mariadb-service
  base:
    container_name: "datos"
    image: "jorgelfant/kuberneteswildflydb:latest"
    ports:
      - "3306:3306"
